### ISSUE TITLE
CORS preflight issue

### ISSUE THREAD

**Issue by jmbott** [redivis/redivis-js#5]
I started having a CORS issue on https://qsel.columbia.edu/cwp-epu-data-platform a couple hours ago. It occurs when pulling data from redivis. I figured it was my issue but I am getting the same error with the demo redivis-js notebook. Both issues are with the CORS preflight request. Using the python redivis client library seems to work fine. 

<img width="1463" alt="Screen Shot 2022-05-04 at 8 48 03 PM" src="https://user-images.githubusercontent.com/7769317/166849331-eda8b279-61cf-48c5-aeed-f2087fa0da47.png">

Do you know what the cause could be? There don't seem to be any recent changes here so I will keep checking my side.

**Comment by jmbott** [comment]
On the `cwp-data-platform` I did make changes yesterday but I have tried
* reverting those changes locally
* rolling back the last redivis data release
* [this demo](https://observablehq.com/d/f770d6d1d0b6bc5b) and the `cwp-data-platform` on multiple computers/browsers
* using an "Allow CORS" extension on chrome
* updating all node packages locally

**Comment by imathews** [comment]
@jmbott thanks so much for opening this issue. There was a recent config change on our servers that caused an issue with CORS preflight requests, which is only relevant when the API is called from a browser environment (which is why you were seeing this in the JS examples but not in python).

A fix just went live; all should be working now. Apologies for the headaches in tracking this down
